name: oidc-poc
on:
    push:
        branches:
            - '*'
jobs:
    auth:
        permissions:
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        steps:
            - name: Get ID Token
              run: |
                    ID_TOKEN=$(curl -sLS -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
                    "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=jfrog-github" | jq .value | tr -d '"')
                    echo "ID_TOKEN=${ID_TOKEN}" >> $GITHUB_ENV

            - name: Exchange Token for Access Token
              env:
                    ID_TOKEN: ${{ env.ID_TOKEN }}
                    JFROG_PLATFORM_URL: https://hts2.jfrog.io
              run: |
                    ACCESS_TOKEN=$(curl -XPOST -H "Content-Type: application/json" "https://hts2.jfrog.io/access/api/v1/oidc/token" -d "{\"grant_type\": \"urn:ietf:params:oauth:grant-type:token-exchange\", \"subject_token_type\":\"urn:ietf:params:oauth:token-type:id_token\", \"subject_token\": \"${ID_TOKEN}\", \"provider_name\": \"ashritha\"}" | jq .access_token | tr -d '"')
                    echo "ACCESS_TOKEN=${ACCESS_TOKEN}" >> $GITHUB_ENV

            - name: Install numpy from Artifactory
              env:
                    ACCESS_TOKEN: ${{ env.ACCESS_TOKEN }}
              run: |
                    pip install numpy --no-deps --no-cache-dir --extra-index-url https://hts2.jfrog.io/artifactory/ashritha-pypi/simple --trusted-host hts2.jfrog.io --header "Authorization: Bearer ${ACCESS_TOKEN}"
