name: Install Requests with OIDC

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Fetch OIDC Token
        id: oidc
        run: |
          echo "Fetching OIDC token..."
          TOKEN=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://incloudmaster.jfrog.io/artifactory/api/security/v1/token" | jq -r '.token')
          echo "token=$TOKEN" >> $GITHUB_ENV

      - name: Configure pip to use Artifactory
        run: |
          mkdir -p ~/.pip
          echo "[global]" > ~/.pip/pip.conf
          echo "index-url = https://incloudmaster.jfrog.io/artifactory/api/pypi/ashritha-pypi/simple" >> ~/.pip/pip.conf
          echo "[auth]" >> ~/.pip/pip.conf
          echo "basic-auth = ${{ env.token }}" >> ~/.pip/pip.conf

      - name: Install Requests
        run: |
          pip install requests --timeout=60

      - name: Verify installation
        run: |
          python -c "import requests"
