name: Install NumPy from Artifactory

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger on

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use the desired Python version

      - name: Configure pip to use Artifactory
        run: |
          mkdir -p ~/.pip  # Create the .pip directory if it doesn't exist
          echo "[global]" > ~/.pip/pip.conf
          echo "index-url = https://ashrithac:@Password24@incloudmaster.jfrog.io/artifactory/api/pypi/ashritha-pypi/simple" >> ~/.pip/pip.conf
        env:
          USERNAME: '<YOUR_USERNAME>'  # Replace with your Artifactory username
          PASSWORD: '<YOUR_PASSWORD>'  # Replace with your Artifactory password

      - name: Install NumPy
        run: |
          pip install numpy

      - name: Verify installation
        run: |
          python -c "import numpy"  # Verify NumPy is installed
