name: Install Pandas from Artifactory

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Check Artifactory URL
        run: |
          curl -I https://incloudmaster.jfrog.io/artifactory/api/pypi/ashritha-pypi/simple

      - name: Configure pip to use Artifactory
        run: |
          mkdir -p ~/.pip
          echo "[global]" > ~/.pip/pip.conf
          echo "index-url = https://${{ secrets.ARTIFACTORY_USERNAME }}:${{ secrets.ARTIFACTORY_PASSWORD }}@incloudmaster.jfrog.io/artifactory/api/pypi/ashritha-pypi/simple" >> ~/.pip/pip.conf

      - name: Install Pandas
        run: |
          pip install pandas --timeout=60

      - name: Verify installation
        run: |
          python -c "import pandas"
