name: Install Numpy from Artifactory

on:
  push:
    branches:
      - main

jobs:
  install-numpy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify your Python version

    - name: Generate OIDC token
      id: oidc
      run: |
        echo "OIDC_TOKEN=${{ secrets.OIDC_TOKEN }}" >> $GITHUB_ENV  # Adjust this as necessary for your OIDC generation

    - name: Configure pip to use Artifactory
      run: |
        mkdir -p ~/.config/pip
        echo "[global]" > ~/.config/pip/pip.conf
        echo "extra-index-url=https://hts2.jfrog.io/artifactory/api/pypi/ashritha-pypi/simple" >> ~/.config/pip/pip.conf
        echo "[auth]" >> ~/.config/pip/pip.conf
        echo "https://hts2.jfrog.io/ = ${OIDC_TOKEN}" >> ~/.config/pip/pip.conf

    - name: Install Numpy
      run: |
        pip install numpy
